# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            'What Have I Done?'
tagline:          'Building things'
# description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
description:      'is the personal site of <a href="https://github.com/lewisdbentley" target="_blank">@LewisBentley</a>. I will post things here.'
url:              http://hyde.getpoole.com
# baseurl:          /

author:
  name:           'Lewis Bentley'
  url:            https://github.com/lewisdbentley

paginate:         5

# Plugins
# plugins:
#  - jekyll-paginate

# Custom vars
version:          1.0

github:
  repo:           https://github.com/lewisdbentley/whathaveidone
